# Site
repository: JuneKunst/JuneKunst.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 권형중 (June)
name_en: Hyeongjung Kwon (June)
title: Frontend Engineer
title_en: Frontend Engineer
email: hjkwon9401@gmail.com
# email_title: Email (Email title override)
phone: 010-4679-5018
# phone_title: Phone (Phone title override)
# website: https://junekunst.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: JuneKunst
linkedin_username: hyeongjung-kwon-578aa11b5
# Remove unused social links
# twitter_username: jekyllrb
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
  - title: Link name
    icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
    url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
# about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  **MVP부터 누적 사용자 70만명 규모까지** 성장한 중고 패션 이커머스 플랫폼을 3년간 개발한 프론트엔드 엔지니어입니다.

  **멀티플랫폼 생태계** (Flutter 모바일앱, React 웹앱, WMS 관리자) 설계 및 구현 경험과  
  **복잡한 이커머스 도메인**의 기술적 도전을 해결하며 **비즈니스 임팩트**를 창출하는 것에 전문성을 가지고 있습니다.

  **Tech Stack**
  - **Frontend**: Flutter (BLoC), React (TypeScript), PWA
  - **Architecture**: Clean Architecture, Server-Driven UI, Multi-platform
  - **Performance**: 가상화, 캐싱, 이미지 최적화, Bundle splitting

about_content_en: | # this will include new lines to allow paragraphs
  Frontend Engineer with **3 years of experience** developing a fashion e-commerce platform that grew **from MVP to 700K+ users**.

  Specialized in **multi-platform ecosystem** design (Flutter mobile, React web, WMS admin) and solving complex **e-commerce domain challenges** to drive **business impact**.

  **Tech Stack**
  - **Frontend**: Flutter (BLoC), React (TypeScript), PWA
  - **Architecture**: Clean Architecture, Server-Driven UI, Multi-platform
  - **Performance**: Virtualization, Caching, Image Optimization, Bundle Splitting

content:
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: Mine.is (차란)
        title_en: Mine.is (Charan)
        sub_title: Frontend Engineer
        sub_title_en: Frontend Engineer
        caption: 2022.06 ~ 2025.08
        quote: 중고 패션 이커머스 플랫폼 | 누적 사용자 70만명 | 앱스토어 이커머스 1위
        quote_en: Fashion E-commerce Platform | 700K+ Users | #1 E-commerce App Store
        description: |
          **멀티플랫폼 생태계 설계 및 개발**
          - **4개 프론트엔드 앱** 동시 개발/운영 (Flutter 모바일, React 웹앱, 2개 WMS 시스템)
          - **Clean Architecture + BLoC 패턴** 기반 대규모 아키텍처 설계
          - **Server-Driven UI (SDUI)** 구현으로 배포 없는 실시간 UI 업데이트
          - **5개 환경 빌드 시스템** (dev/test/staging/alpha/prod) 구축

          **핵심 기술 성과**
          - **Server-Driven UI Exhibition**: 20+ 원격 구성으로 앱 배포 없는 실시간 기획전 업데이트
          - **Design System**: 130개 재사용 컴포넌트 + Widgetbook 통합으로 개발 효율성 혁신
          - **WMS Full Supply Chain**: 픽업→검수→포장→배송 End-to-End 물류 자동화 시스템
          - **Flutter 3.27.1 → 3.29.3** 대규모 마이그레이션 및 4개 분석 플랫폼 통합

          **이커머스 도메인 전문성**
          - **개인화 추천 시스템** UI/UX 구현 (유사룩, 브랜드 팔로우)
          - **복합 결제 시스템** (포트원, 쿠폰, 포인트) 프론트엔드 개발
          - **실시간 재고 관리** 및 상품 상태 추적 시스템 구현
        description_en: |
          **Multi-platform Ecosystem Design & Development**
          - **4 Frontend Apps** simultaneous development/operation (Flutter mobile, React web, 2 WMS systems)
          - **Clean Architecture + BLoC Pattern** based large-scale architecture design
          - **Server-Driven UI (SDUI)** implementation for real-time UI updates without deployment
          - **5-environment build system** (dev/test/staging/alpha/prod) construction

          **Core Technical Achievements**
          - **Server-Driven UI Exhibition**: 20+ remote configurations for real-time campaign updates without app deployment
          - **Design System**: 130 reusable components + Widgetbook integration revolutionizing development efficiency
          - **WMS Full Supply Chain**: Pickup→Inspection→Packaging→Delivery End-to-End logistics automation system
          - **Flutter 3.27.1 → 3.29.3** large-scale migration and 4 analytics platform integration

          **E-commerce Domain Expertise**
          - **Personalized Recommendation System** UI/UX implementation (similar looks, brand follow)
          - **Complex Payment System** (Portone, coupons, points) frontend development
          - **Real-time Inventory Management** and product status tracking system implementation

  - title: Key Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: 차란 Flutter 네이티브 앱 (Ver.2)
        caption: 2024.12 ~ 2025.06
        additional_links:
          - title: App Store
            icon: fab fa-apple
            url: https://apps.apple.com/kr/app/차란/id1234567890
        quote: >
          **React 웹뷰 → Flutter 네이티브** 대규모 마이그레이션 프로젝트
        description: | # this will include new lines to allow paragraphs
          - **WebView-Native 하이브리드 아키텍처** 구현 (20+ JavaScript 핸들러)
          - **BLoC 패턴** 기반 15개 서비스 계층 및 10개 Repository 설계
          - **멀티 Flavor 빌드** 시스템으로 환경별 Firebase 프로젝트 분리
          - **Codemagic CI/CD** + **Shorebird** 도입으로 심사 없는 앱 업데이트 환경 구축

      - layout: left
        border: weak
        title: 차란 React 웹앱 (Ver.1)
        caption: 2022.06 ~ 2024.12
        quote: >
          **MVP → 70만 사용자** 성장을 이끈 초기 프론트엔드 개발
        description: | # this will include new lines to allow paragraphs
          - **React 18 + TypeScript** 기반 대규모 SPA 아키텍처 설계
          - **Recoil + React Query** 조합으로 30+ 전역 상태 최적화
          - **Atomic Design** 원칙 기반 100+ 컴포넌트 라이브러리 구축
          - **Vite 빌드 시스템** 및 Bundle Splitting으로 성능 최적화

      - layout: left
        title: CORE WMS (창고관리시스템)
        caption: 2023.01 ~ 2024.06
        quote: >
          **B2B 물류 시스템** 프론트엔드 전담 개발
        description: | # this will include new lines to allow paragraphs
          - **React 17 + Material-UI 5** 기반 복잡한 비즈니스 로직 구현
          - **QR/바코드 스캐닝** 시스템 및 실시간 상품 추적 UI 개발
          - **가상화 테이블** (react-virtuoso) 구현으로 대용량 데이터 렌더링 최적화
          - **ZPL 프린터 연동** 및 운송장 자동 생성 시스템 구축

  - title: Technical Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Frontend Framework & Language**  
      Flutter (3+ years) • React (3+ years) • TypeScript • JavaScript ES6+

      **State Management & Architecture**  
      BLoC Pattern • Recoil • React Query • Redux • Clean Architecture • MVVM

      **Performance & Optimization**  
      가상화 (react-virtuoso) • Bundle Splitting • 이미지 최적화 • PWA • Caching Strategy

      **Development & Collaboration**  
      Git/GitHub • CI/CD (Codemagic) • Firebase • Figma • Storybook • Widgetbook

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme # (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
